spring:
  application:
    name: rms-backend
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

rms:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000
